- name: KAMAILIO Kamailio installation and configuration
  hosts: prodenv-aio
  tags:
    - aio
    - voice
    - kamailio
  vars:
    install_prefix: /opt/omnileads
    packages_url: https://fts-public-packages.s3.amazonaws.com
    kamailio_package: "{{ packages_url }}/kamailio/kamailio_{{ kamailio_version }}_amd64.deb"
    kamailio_location: "{{ install_prefix }}/kamailio"
    certs_location: "/etc/kamailio/certs"
    debian_version: "bullseye"
  tasks:

    # Environment variables setting
    - name: KAMAILIO Setting of environment variables
      copy:
        dest: "/etc/default/kamailio"
        content: |
          KAMAILIO_HOSTNAME={{ kamailio_host }}
          KAMAILIO_CERTS_LOCATION={{ certs_location }}
          ASTERISK_HOSTNAME={{ asterisk_host }}
          REDIS_HOSTNAME={{ redis_host }}
          RTPENGINE_HOSTNAME={{ rtpengine_host }}
          SHM_SIZE={{ shm_size }}
          PKG_SIZE={{ pkg_size }}

          export KAMAILIO_HOSTNAME KAMAILIO_CERTS_LOCATION ASTERISK_HOSTNAME REDIS_HOSTNAME RTPENGINE_HOSTNAME SHM_SIZE PKG_SIZE

      # Add an Apt signing key, uses whichever key is at the URL
    - apt_key:
        url: "http://deb.kamailio.org/kamailiodebkey.gpg"
        state: present

    - name: KAMAILIO Add specified repository into sources list
      apt_repository:
        repo: deb http://deb.kamailio.org/kamailio56 bullseye main
        state: present

    - name: KAMAILIO Apt update
      command: apt update

    - name: KAMAILIO Install Kamailio dependencies
      apt:
        name:
          - libhiredis-dev
          - uuid-dev
          - net-tools
          - sngrep
          - kamailio
          - kamailio-python3-modules
          - kamailio-autheph-modules
          - kamailio-redis-modules
          - kamailio-outbound-modules
          - kamailio-tls-modules
          - kamailio-extra-modules
          - kamailio-websocket-modules
        state: present


    - name: KAMAILIO Create custom conf files folder
      file:
        path:  "/etc/kamailio/certs"
        state: directory
        owner: kamailio
        group: kamailio
        mode: 0777

    - name: KAMAILIO Copy certs
      copy:
        src: "{{ kamailio_location }}certs/cert.pem"
        dest: /etc/kamailio/certs/
        owner: kamailio
        group: kamailio
        mode: 0777

    - name: KAMAILIO Copy certs
      copy:
        src: "{{ kamailio_location }}certs/key.pem"
        dest: /etc/kamailio/certs/
        owner: kamailio
        group: kamailio
        mode: 0777

    - name: KAMAILIO Copy kamailio.cfg
      copy:
        src: "{{ kamailio_location }}../source/conf/kamailio.cfg"
        dest: /etc/kamailio/kamailio.cfg

    - name: KAMAILIO Copy kamailio.service Systemd file
      copy:
        src: "{{ kamailio_location }}templates/kamailio.service"
        dest: /etc/systemd/system/omnileads-kamailio.service

    - name: KAMAILIO stop and disable a kamailio apt service
      service:
        name: kamailio
        state: stopped
        enabled: false

    # Kamailio restart
    - name: KAMAILIO Restart kamailio service
      systemd:
        name: omnileads-kamailio
        state: restarted
        enabled: yes
        daemon_reload: yes
      tags: always
