- name: Kamailio installation and configuration
  hosts: prodenv-aio
  vars:
    install_prefix: /opt/omnileads
  tasks:

    # Se cargan las variavles para el playbook
    - name: Loading variables por playbook
      include_vars: vars.yml
      when: kamailio_out is defined

    # se crea el grupo de usuario omnileads
    - name: Creation of {{ usuario }} group
      group: name={{ usuario }} state=present
      when: kamailio_out is defined

    # Se crea el usuario omnileads con home en /opt/omnileads y con llaves ssh generadas
    - name: Creation of {{ usuario }} user
      user: name={{ usuario }} group={{ usuario }} create_home=yes shell=/bin/bash home=/opt/{{ usuario }} generate_ssh_key=yes ssh_key_bits=2048 state=present
      when: kamailio_out is defined

    # Se instala repo epel
    - name: Install epel repository
      command: yum install epel-release -y
      when: kamailio_out is defined

    - name: Set of environments variables
      copy:
        dest: "/etc/profile.d/omnileads_envars.sh"
        content: |
          KAMAILIO_HOSTNAME={{ kamailio_hostname }}
          KAMAILIO_CERTS_LOCATION={{ certs_location }}
          ASTERISK_HOSTNAME={{ asterisk_hostname }}
          REDIS_HOSTNAME={{ redis_hostname }}
          RTPENGINE_HOSTNAME= {{ rtpengine_hostname }}
          SHM_SIZE={{ shm_size }}
          PKG_SIZE={{ pkg_size }}

          export KAMAILIO_HOSTNAME KAMAILIO_CERTS_LOCATION ASTERISK_HOSTNAME REDIS_HOSTNAME RTPENGINE_HOSTNAME SHM_SIZE PKG_SIZE
      when: kamailio_out is defined

    # Chequeo si la version de kamailio instalada es {{ kamailio_version }}
    - name: Check if kamailio OMniLeads package {{ kamailio_version }} is installed
      shell:  yum list installed |grep kamailio | awk -F " " '{print $2}' |awk -F "-" '{print $1}'
      register: kamailio_installed
      changed_when: false
      tags: postinstall

    # Se imprime que el kamailio OMniLeads configuration no esta instalado si la version actual es inferior a la requerida
    - debug: msg="kamailio OMniLeads {{ kamailio_version }} is not installed, proceeding to install"
      when: kamailio_installed.stdout != kamailio_version
      tags: postinstall

    # Por lo contrario se imprime que ya está instalada la version mas actual
    - debug: msg="kamailio OMniLeads package is already installed in version {{ kamailio_version }}, skipping installation steps"
      when: kamailio_installed.stdout == kamailio_version
      tags: postinstall

    # Esta tarea es para eliminar paquete viejo de virtualenv generar inconsistencia de binarios
    - name: Delete old kamailio OMniLeads package
      yum: name=omnileads-kamailio state=absent
      tags: postinstall
      when: kamailio_installed.stdout != kamailio_version

    # Se instala el paquete de websockets
    - name: Install kamailio OMniLeads {{ kamailio_version }} package (from s3 source)
      yum: name={{ kamailio_package }} state=latest update_cache=yes
      tags: postinstall
      retries: 3
      delay: 3
      register: s3_download
      until: s3_download is success
      when: kamailio_installed.stdout != kamailio_version

    # Se pasan los certificados creados en kamailio a la carpeta kamailio_certs
    - name: Copy of the certificates in kamailio
      copy: "src={{ repo_location }}/ansible/deploy/certs/{{ item }} dest={{ certs_location }}"
      with_items:
        - cert.pem
        - key.pem
      
    # Linkeamos dos binarios de kamailio que son necesarios para el buen funcionamiento del proceso de autenticacion
    - name: Link kamcmd binarie to /usr/sbin
      file: state=link src={{ kamailio_location }}/sbin/kamcmd dest=/usr/sbin/kamcmd mode=755 force=true

    - name: Link kamctl binarie to /usr/sbin
      file: state=link src={{ kamailio_location }}/sbin/kamctl dest=/usr/sbin/kamctl mode=755 force=true

    # Starteo y habilito kamailio
    - name: Restart of kamailio
      service: name=kamailio state=restarted enabled=yes daemon_reload=yes
      tags: postinstall
