- name: Kamailio installation and configuration
  hosts: prodenv-aio
  vars:
    install_prefix: /opt/omnileads
    packages_url: https://fts-public-packages.s3.amazonaws.com
    kamailio_package: "{{ packages_url }}/kamailio/kamailio-{{ kamailio_version }}.x86_64.rpm"
    kamailio_location: "{{ install_prefix }}/kamailio"
  tasks:

    - name: Set of environments variables
      copy:
        dest: "/etc/profile.d/omnileads_envars.sh"
        content: |
          KAMAILIO_HOSTNAME={{ kamailio_hostname }}
          KAMAILIO_CERTS_LOCATION={{ certs_location }}
          ASTERISK_HOSTNAME={{ asterisk_hostname }}
          REDIS_HOSTNAME={{ redis_hostname }}
          RTPENGINE_HOSTNAME= {{ rtpengine_hostname }}
          SHM_SIZE={{ shm_size }}
          PKG_SIZE={{ pkg_size }}

          export KAMAILIO_HOSTNAME KAMAILIO_CERTS_LOCATION ASTERISK_HOSTNAME REDIS_HOSTNAME RTPENGINE_HOSTNAME SHM_SIZE PKG_SIZE
      when: kamailio_out is defined

    # Chequeo si la version de kamailio instalada es {{ kamailio_version }}
    - name: Check if kamailio OMniLeads package {{ kamailio_version }} is installed
      shell:  yum list installed |grep kamailio | awk -F " " '{print $2}' |awk -F "-" '{print $1}'
      register: kamailio_installed
      changed_when: false
      tags: postinstall

    # Se imprime que el kamailio OMniLeads configuration no esta instalado si la version actual es inferior a la requerida
    - debug: msg="kamailio OMniLeads {{ kamailio_version }} is not installed, proceeding to install"
      when: kamailio_installed.stdout != kamailio_version
      tags: postinstall

    # Por lo contrario se imprime que ya está instalada la version mas actual
    - debug: msg="kamailio OMniLeads package is already installed in version {{ kamailio_version }}, skipping installation steps"
      when: kamailio_installed.stdout == kamailio_version
      tags: postinstall

    # Esta tarea es para eliminar paquete viejo de virtualenv generar inconsistencia de binarios
    - name: Delete old kamailio OMniLeads package
      yum: name=omnileads-kamailio state=absent
      tags: postinstall
      when: kamailio_installed.stdout != kamailio_version

    # Se instala el paquete de websockets
    - name: Install kamailio OMniLeads {{ kamailio_version }} package (from s3 source)
      yum: name={{ kamailio_package }} state=latest update_cache=yes
      tags: postinstall
      retries: 3
      delay: 3
      register: s3_download
      until: s3_download is success
      when: kamailio_installed.stdout != kamailio_version
